version: '3.2'
services:
  web-app:
    build: .
    depends_on:
      - my-db
    ports:
      - 8080:8080
    restart: on-failure
  my-db:
    image: postgres:latest
    container_name: my-db
    ports:
      - 5432:5432
    restart: on-failure
    volumes:
      - my-db:/db/data
    environment:
      - POSTGRES_DB=university
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
volumes:
  my-db: